// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA329Q9NQUD0I5FCs2xh4RiOBM7Jqx8JvM',
    appId: '1:778391359442:web:fc09fdf1edee2a006b820b',
    messagingSenderId: '778391359442',
    projectId: 'grocerryapp-f0535',
    authDomain: 'grocerryapp-f0535.firebaseapp.com',
    storageBucket: 'grocerryapp-f0535.appspot.com',
    measurementId: 'G-QZ5K3HH6PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0mPINGRyW1z5zX-OpA0nRbxJRJtS9Yms',
    appId: '1:778391359442:android:ce6e676f9151a97d6b820b',
    messagingSenderId: '778391359442',
    projectId: 'grocerryapp-f0535',
    storageBucket: 'grocerryapp-f0535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAInrEBdRxKe2w0PUNu31itw5pOUglFc8',
    appId: '1:778391359442:ios:b0bd53c0ac4b28a06b820b',
    messagingSenderId: '778391359442',
    projectId: 'grocerryapp-f0535',
    storageBucket: 'grocerryapp-f0535.appspot.com',
    androidClientId: '778391359442-4ru96rh5rqsojurrv5oc1dcf6g2fd17d.apps.googleusercontent.com',
    iosClientId: '778391359442-4l3ubqet12nmgk56bik7qv3jb2dbq8ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.xApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAInrEBdRxKe2w0PUNu31itw5pOUglFc8',
    appId: '1:778391359442:ios:e71d5ec0774a6c106b820b',
    messagingSenderId: '778391359442',
    projectId: 'grocerryapp-f0535',
    storageBucket: 'grocerryapp-f0535.appspot.com',
    androidClientId: '778391359442-4ru96rh5rqsojurrv5oc1dcf6g2fd17d.apps.googleusercontent.com',
    iosClientId: '778391359442-sj7ikomcd5pgr6nqpe8ia12jl5aljj4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.xApp.RunnerTests',
  );
}
